title: lcfu1的博客
author: lcfu1
email: 1711648344@qq.com
description: > # this means to ignore newlines until "baseurl:"
  一个喜欢分享的懒博主！极简主义者！Geek！
  这里的文章不是固定不变的，会随着我个人的学习情况不定期修改完善，加油！

#twitter_username: jekyllrb
github_username:  lcfu1

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
exclude:
  - Gemfile
  - Gemfile.lock
